# Generated by Django 3.2 on 2021-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_category_create_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SLUG'),
        ),
    ]
