# Generated by Django 3.2 on 2021-05-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
