# Generated by Django 3.2 on 2021-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_auto_20210508_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
