# Generated by Django 3.2 on 2021-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='check_medicine',
            field=models.BooleanField(default=True),
        ),
    ]
