# Generated by Django 3.2 on 2021-05-02 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-modify_dt',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
    ]
