# Generated by Django 3.1.5 on 2021-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_auto_20210502_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
