# Generated by Django 3.2 on 2021-05-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_auto_20210503_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
